WIP: windows workflow on ci

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -13,9 +13,10 @@ on:
     types: rebuild
 
 jobs:
-  tests:
-    name: "Python ${{ matrix.python-version }}"
-    runs-on: "ubuntu-latest"
+  # just trying something out
+  tests-windows:
+    name: "Python ${{ matrix.python-version }} on Windows"
+    runs-on: "windows-latest"
     env:
       USING_COVERAGE: '3.7,3.8'
     strategy:
@@ -28,48 +29,73 @@ jobs:
           python-version: "${{ matrix.python-version }}"
       - name: "Install dependencies"
         run: |
-          set -xe
-          python -VV
-          python -m site
           python -m pip install --upgrade pip setuptools wheel
           python -m pip install --upgrade virtualenv tox tox-gh-actions
       - name: "Run tox targets for ${{ matrix.python-version }}"
         run: "python -m tox"
-      - name: "Upload coverage to Codecov"
-        if: "contains(env.USING_COVERAGE, matrix.python-version)"
-        uses: "codecov/codecov-action@v1"
-        with:
-          file: ./coverage.xml
-          fail_ci_if_error: true
+      # - name: "Upload coverage to Codecov"
+      #   if: "contains(env.USING_COVERAGE, matrix.python-version)"
+      #   uses: "codecov/codecov-action@v1"
+      #   with:
+      #     file: ./coverage.xml
+      #     fail_ci_if_error: true
+  # tests:
+  #   name: "Python ${{ matrix.python-version }}"
+  #   runs-on: "ubuntu-latest"
+  #   env:
+  #     USING_COVERAGE: '3.7,3.8'
+  #   strategy:
+  #     matrix:
+  #       python-version: ["3.5", "3.6", "3.7", "3.8"]
+  #   steps:
+  #     - uses: "actions/checkout@v2"
+  #     - uses: "actions/setup-python@v1"
+  #       with:
+  #         python-version: "${{ matrix.python-version }}"
+  #     - name: "Install dependencies"
+  #       run: |
+  #         set -xe
+  #         python -VV
+  #         python -m site
+  #         python -m pip install --upgrade pip setuptools wheel
+  #         python -m pip install --upgrade virtualenv tox tox-gh-actions
+  #     - name: "Run tox targets for ${{ matrix.python-version }}"
+  #       run: "python -m tox"
+  #     - name: "Upload coverage to Codecov"
+  #       if: "contains(env.USING_COVERAGE, matrix.python-version)"
+  #       uses: "codecov/codecov-action@v1"
+  #       with:
+  #         file: ./coverage.xml
+  #         fail_ci_if_error: true
 
-  package:
-    name: "Build & verify package"
-    runs-on: "ubuntu-latest"
+  # package:
+  #   name: "Build & verify package"
+  #   runs-on: "ubuntu-latest"
 
-    steps:
-      - uses: "actions/checkout@v2"
-      - uses: "actions/setup-python@v1"
-        with:
-          python-version: "3.8"
-      - name: "Install pep517 and twine"
-        run: "python -m pip install pep517 twine"
-      - name: "Build package"
-        run: "python -m pep517.build --source --binary ."
-      - name: "List result"
-        run: "ls -l dist"
-      - name: "Check long_description"
-        run: "python -m twine check dist/*"
+  #   steps:
+  #     - uses: "actions/checkout@v2"
+  #     - uses: "actions/setup-python@v1"
+  #       with:
+  #         python-version: "3.8"
+  #     - name: "Install pep517 and twine"
+  #       run: "python -m pip install pep517 twine"
+  #     - name: "Build package"
+  #       run: "python -m pep517.build --source --binary ."
+  #     - name: "List result"
+  #       run: "ls -l dist"
+  #     - name: "Check long_description"
+  #       run: "python -m twine check dist/*"
 
-  install-dev:
-    name: "Verify dev env"
-    runs-on: "ubuntu-latest"  # todo: maybe add windows & mac
+  # install-dev:
+  #   name: "Verify dev env"
+  #   runs-on: "ubuntu-latest"  # todo: maybe add windows & mac
 
-    steps:
-      - uses: "actions/checkout@v2"
-      - uses: "actions/setup-python@v1"
-        with:
-          python-version: "3.8"
-      - name: "Install in dev mode"
-        run: "python -m pip install -e .[dev]"
-      - name: "Import package"
-        run: "python -c 'import interrogate; print(interrogate.__version__)'"
+  #   steps:
+  #     - uses: "actions/checkout@v2"
+  #     - uses: "actions/setup-python@v1"
+  #       with:
+  #         python-version: "3.8"
+  #     - name: "Install in dev mode"
+  #       run: "python -m pip install -e .[dev]"
+  #     - name: "Import package"
+  #       run: "python -c 'import interrogate; print(interrogate.__version__)'"
